### ISSUE TITLE
How to get the busybox image with v1 manifest

### ISSUE THREAD

**Issue by smaistry** [docker-library/busybox#135]
How to get the busybox image with v1 manifest?

"application/vnd.docker.distribution.manifest.v1+json"
"application/vnd.docker.distribution.manifest.v1+prettyjws"
"application/vnd.oci.image.manifest.v1+json"
"application/vnd.docker.distribution.manifest.v2+json"

**Comment by wglambert** [comment]
v1 was deprecated some time ago https://www.docker.com/blog/registry-v1-api-deprecation/

There was also this discussion in golang about v1/v2 https://github.com/docker-library/golang/issues/269#issuecomment-473094518
>We have no control over what the hub gives us back when we push an image . . . some pushed as v2 and some as v1
