### ISSUE TITLE
Add SIGTERM Support

### ISSUE THREAD

**Issue by nickkeane** [docker-library/busybox#139]
Docker expects containers to respond to SIGTERM to shut down safely. It currently looks like the busybox container is getting shut down after 10 seconds on my server.

https://docs.docker.com/engine/reference/commandline/stop/

**Comment by yosifkit** [comment]
:confused: `busybox` is just a collection of tools, so depending on what you are running it may or may not respond to a `SIGTERM`. There is anything we could do in the image for that.
