### ISSUE TITLE
exit builtin broken in /bin/sh

### ISSUE THREAD

**Issue by samuelkarp** [docker-library/busybox#2]
Hello,

The latest image at `busybox:latest` (Digest: sha256:c583946ffce98766427b21c9f6bed5ca1cb3dfa46188d1e5a122854dff0c1b76) appears to have a broken `sh`. Here's an example:

```
$ docker run busybox@sha256:c583946ffce98766427b21c9f6bed5ca1cb3dfa46188d1e5a122854dff0c1b76 sh -c 'sh -c "exit 0"; echo $?'
Segmentation fault
139
```

The previous image I was using (looks to be similar to `busybox:buildroot-2014.02`) (Digest: sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507) behaves closer to how I expect:

```
$ docker run busybox@sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507 sh -c 'sh -c "exit 0"; echo $?'
0
```

And since I'm sure you want to see how I'm running this:

```
$ docker info
Containers: 6
Images: 199
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 213
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 4
Total Memory: 15.53 GiB
Name: u8c89a5b74c6750492784
ID: KXI5:FAAI:Y2OH:RMMF:OSCX:XUO5:NTJP:7A6N:RIAR:S4GU:EJFA:7X55
WARNING: No swap limit support
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

Thanks,
Sam

**Comment by tianon** [comment]
Apparently there's a lot more than just `exit` broken (thanks to @estesp's userns army for pointing it out), so `busybox` is currently reverted back to @jpetazzo's older one while we figure out what went wrong and fix it. :+1:

(This time adding a test to https://github.com/docker-library/official-images/tree/master/test/tests to make sure we don't have something so blatantly broken get merged again.)

**Comment by tianon** [comment]
(Also, thanks so much for the detailed report, @samuelkarp!)
