### ISSUE TITLE
busybox:1.25.1 contains DDoS Trojan Mirai

### ISSUE THREAD

**Issue by rhuss** [docker-library/busybox#29]
According to virustotal.com, busybox:1.25.1 contains the Busybox Trojan Mirai.

See https://github.com/fabric8io/docker-maven-plugin/issues/795 for details.

**Comment by NathanMcCauley** [comment]
This seems to be a false positive due to a signature in one of the scanners in VirusTotal. Its detecting a stock BusyBox binary. The binary is normal size and doesn't contain any of the strings that are typically contained in Mirai samples. I've submitted a false positive report to the scanner.

**Comment by rhuss** [comment]
Thanks for the investigation.

**Comment by tianon** [comment]
@NathanMcCauley thanks for looking into this and reporting it downstream! :heart:

Indeed, we simply compile BusyBox from upstream's source, and that becomes the binary that provides `/bin/[` in the image. :+1:
