### ISSUE TITLE
 How can I compile busysbox.tar.xz

### ISSUE THREAD

**Issue by jcxian** [docker-library/busybox#37]
I've successfully compiled the busybox source on the mips64le architecture system,
How can I package as busybox.tar.xz?
Can anyone help me?

**Comment by yosifkit** [comment]
For all our arches we just use the build script:

https://github.com/docker-library/busybox/blob/59a7bffbd98b97bb5c5467157530987f9f595afa/build.sh#L18

Which takes advantage of the work done in the Dockerfile.builder to setup the contents for the tar: 

https://github.com/docker-library/busybox/blob/59a7bffbd98b97bb5c5467157530987f9f595afa/glibc/Dockerfile.builder#L78-L142

**Comment by jcxian** [comment]
I found "FROM debian:stretch-slim" from Dockerfile.builder. there's no debian:stretch-slim for mips64le architecture. how can i do for it?

**Comment by tianon** [comment]
Just to thread the needle, see https://github.com/debuerreotype/docker-debian-artifacts/issues/23 (issue filed with the same question following this one).
