### ISSUE TITLE
Exception observed for the base image of busybox

### ISSUE THREAD

**Issue by arm64b** [docker-library/busybox#42]
If the busybox use `debian:stretch-slim` as the base image of the busybox, then we'll have the issue reported by https://github.com/moby/moby/issues/35963, if we switch the base image from `debian:jessie-slim`, then the issue will not show. I guess the busybox binary has some kind of conflicts with the pkg(s) in the rootfs of `debian:stretch-slim`, but now can't narrow down which one(s).

**Comment by tianon** [comment]
I cannot reproduce the failure described there for _any_ of the supported variants of the current image: :confused:

```console
$ docker network create --driver=bridge --internal internal
13bf6ff0af3851b7d91e014f62832b396edbd97a615dff0146ee0e9b6a1f7169

$ for variant in uclibc glibc musl; do echo; echo "Testing $variant"; echo; docker pull "busybox:$variant" && docker run -d --name first --network internal "busybox:$variant" top && docker run -d --name second --network internal "busybox:$variant" top && docker exec first ping -c1 second && docker exec second ping -c1 first; docker rm -vf first second; echo; done

Testing uclibc

uclibc: Pulling from library/busybox
Digest: sha256:0653505dd1111d1e70462d124051074fadaeeb7803ce2cff14fb4ca49a304da5
Status: Image is up to date for busybox:uclibc
7aacbf3799f1e49e9e3a07b9c85fe216a8014b17b3a4ed8bc79702a216475ab7
5a1228742b2a5dbdb076e4a28b6d5164253e46a9c0b939cfc05976ef6273ca23
PING second (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: seq=0 ttl=64 time=0.066 ms

--- second ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.066/0.066/0.066 ms
PING first (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.032 ms

--- first ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.032/0.032/0.032 ms
first
second


Testing glibc

glibc: Pulling from library/busybox
Digest: sha256:973d8845ad1bdf0d9d2647e8b99701b7e45a195667cfd42e46a1140afe4da8ab
Status: Image is up to date for busybox:glibc
b8b1687d64f90b60be6edd9154019d29364dfe7bf36dc0b1568cc1ab3c225c66
9d3c0a1fef9be224119c96f1a027892e99b86c2ceb9212ce578ef514b4828a40
PING second (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: seq=0 ttl=64 time=0.077 ms

--- second ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.077/0.077/0.077 ms
PING first (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.049 ms

--- first ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.049/0.049/0.049 ms
first
second


Testing musl

musl: Pulling from library/busybox
Digest: sha256:3d47144ab6b0f1d99930f7f9551828c0b167618baff06701670b448dd5eef63e
Status: Image is up to date for busybox:musl
28034a79ac8bf8b3ff955cf56d82389c60937188c377ac37d3b412f03a180d2c
c44039ecf59ad6975d06fd4adcf31bd443d1858c6cbdcd6a309ab96147115a50
PING second (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: seq=0 ttl=64 time=0.057 ms

--- second ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.057/0.057/0.057 ms
PING first (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.034 ms

--- first ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.034/0.034/0.034 ms
first
second
```

**Comment by arm64b** [comment]
Hello @tianon , this is very weird and frankly I have no idea about the root cause why the latest busybox image will trigger the test case fail in the PR https://github.com/moby/moby/pull/35929 on amd64 😵 , today I re-run the testing step mentioned in moby/moby#35963, I found that the testing step is a little bit unreliable and not close to the real environment where the test case failed. So I re-design the below steps how to reproduce it(we need to create a docker-in-docker which like the `test-integration` does):
1. `git pull` the latest moby code
2.  `make binary`
3. `docker run --rm -i --privileged  --name moby-docker -e DOCKER_CROSSPLATFORMS -e BUILD_APT_MIRROR -e BUILDFLAGS -e KEEPBUNDLE -e DOCKER_BUILD_ARGS -e DOCKER_BUILD_GOGC -e DOCKER_BUILD_PKGS -e DOCKER_BASH_COMPLETION_PATH -e DOCKER_CLI_PATH -e DOCKER_DEBUG -e DOCKER_EXPERIMENTAL -e DOCKER_GITCOMMIT -e DOCKER_GRAPHDRIVER -e DOCKER_INCREMENTAL_BINARY -e DOCKER_LDFLAGS -e DOCKER_PORT -e DOCKER_REMAP_ROOT -e DOCKER_STORAGE_OPTS -e DOCKER_USERLANDPROXY -e TEST_INTEGRATION_DIR -e TESTDIRS -e TESTFLAGS -e TIMEOUT -e HTTP_PROXY -e HTTPS_PROXY -e NO_PROXY -e http_proxy -e https_proxy -e no_proxy -e VERSION -e PLATFORM -v "/home/dennis/workspace/container/moby/moby/bundles:/go/src/github.com/docker/docker/bundles" -v /home/dennis/workspace/container/moby/moby/.git:/go/src/github.com/docker/docker/.git -v "dockerdev-go-pkg-cache-gopath:/go/pkg" -v "dockerdev-go-pkg-cache-goroot-linux_amd64:/usr/local/go/pkg/linux_amd64" -v "dockerdev-go-pkg-cache-goroot-linux_amd64_netgo:/usr/local/go/pkg/linux_amd64_netgo"    -t "docker-dev:moby-network-test" /bin/bash`
3. Now we will be in the shell of the `docker-dev:moby-network-test` container, run below command:
 `root@ff0e101d6031:/go/src/github.com/docker/docker# hack/make.sh binary`
4. run the docker daemon in the container:
`root@ff0e101d6031:/go/src/github.com/docker/docker/bundles/binary-daemon# ./dockerd`
5. **Open another terminal**, in that terminal run below command to enter into the shell of the `moby-docker` container created in step 3: 
`docker exec  -it moby-docker /bin/bash`
6. in the new shell environment from above step 6, we can run the test case manually like this:
`docker network create --driver=bridge --internal internal`
`docker pull  busybox:latest`
`docker run -d --name first --network internal busybox:latest top`
`docker run -d --name second --network internal busybox:latest top`
`docker exec first ping -c 1 second`
The last command will show below error: 
`ping: bad address 'second'`

Interesting, if I switch the `docker pull busybox:latest` to `docker pull busybox:glibc`, then the issue will not show. Unfortunately the test case in `integration-test` just uses the `busybox:latest` image 🤒 

Another information for you reference:
```
root@0787a06db536:/go/src/github.com/docker/docker/bundles/binary-daemon# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             glibc               1be254b766cc        6 days ago          4.4MB
busybox             latest              f9b6f7f7b9d3        6 days ago          1.14MB
```
From above output the busybox:latest image is smaller than glibc's.  And I build my own image with:
`/docker-busybox/busybox# ./build glibc`, the image size is also 4.4MB:
```
docker-busybox/busybox#docker images | grep busybox
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             glibc-test          3f1474f7ce82        45 minutes ago      4.4MB
```

**Comment by tianon** [comment]
I still cannot reproduce, even using Docker-in-Docker with a very recent build of moby master (`tianon/docker-master:dind` is essentially the https://hub.docker.com/_/docker/ official image, but pulling binaries from https://master.dockerproject.org/ instead): :confused:

```console
$ docker pull tianon/docker-master:dind
dind: Pulling from tianon/docker-master
Digest: sha256:74c8178acac4ccaf3fa1ddc58c8d461c5085c0cdea97ec5234cbc53cbe7c772a
Status: Image is up to date for tianon/docker-master:dind

$ docker run --rm tianon/docker-master:dind docker -v
Docker version master-dockerproject-2018-01-21, build 44a1168a

$ docker run -dit --privileged --name dind-master tianon/docker-master:dind --storage-driver overlay2
97f16c44091f53bec74ea6948236ef848f6c738a4329e362dfa9a2af5b39beda

$ docker logs --tail=2 dind-master
INFO[2018-01-22T19:01:47.705490598Z] API listen on [::]:2375                      
INFO[2018-01-22T19:01:47.705497483Z] API listen on /var/run/docker.sock           

$ docker exec -it dind-master sh

/ # docker version
Client:
 Version:	master-dockerproject-2018-01-21
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	44a1168a
 Built:	Sun Jan 21 23:42:06 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	master-dockerproject-2018-01-21
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	db5c006
  Built:	Sun Jan 21 23:50:23 2018
  OS/Arch:	linux/amd64
  Experimental:	false

/ # docker network create --driver=bridge --internal internal
90e55cf0d8ae4f9b20c41e28c6d502cfad17e42fef8a37e17c7307ed6e854a19

/ # for variant in uclibc glibc musl; do echo; echo "Testing $variant"; echo; docker pull "busybox:$variant" && docker run -d --name first --network internal "busybox:$variant" top && docker run -d --name second --network internal "busybox:$variant" top && docker exec first ping -c1 second && docker exec second ping -c1 first; docker rm -vf first second; echo; done

Testing uclibc

uclibc: Pulling from library/busybox
67a0688b88df: Pull complete 
Digest: sha256:0653505dd1111d1e70462d124051074fadaeeb7803ce2cff14fb4ca49a304da5
Status: Downloaded newer image for busybox:uclibc
a3394bee2f776d14ab5654c7b1d2a2b6d27f56bbdaaedcb87dcaf951fc04aea6
2eee78d00e9333b47abaa46848274be8900b5eb9d652cbbde6bc7850403a22c8
PING second (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: seq=0 ttl=64 time=0.052 ms

--- second ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.052/0.052/0.052 ms
PING first (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.037 ms

--- first ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.037/0.037/0.037 ms
first
second


Testing glibc

glibc: Pulling from library/busybox
a8923b406ea9: Pull complete 
Digest: sha256:973d8845ad1bdf0d9d2647e8b99701b7e45a195667cfd42e46a1140afe4da8ab
Status: Downloaded newer image for busybox:glibc
1100b28356d435318ae2c1f5fed150c73ee93765a98c58d965f5e951049767a2
5dd204b3b66494165ce9771c532ee183726daf847455e2bfaa6eddc590f6597f
PING second (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: seq=0 ttl=64 time=0.048 ms

--- second ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.048/0.048/0.048 ms
PING first (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.037 ms

--- first ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.037/0.037/0.037 ms
first
second


Testing musl

musl: Pulling from library/busybox
f24e62b67df5: Pull complete 
Digest: sha256:c3bce2f7ee36a097440c03cf9c1ec88e6eaf32446de88b61dd9387b5f7395fec
Status: Downloaded newer image for busybox:musl
79feb7dc62e98963f6ae5b93ad8d74521e80ba65f87027c377104efb23b0bf73
ad97ec2f3248910d4aaacb751b50c5ec589800bf9a8e9d2baec4a866b7aaea53
PING second (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: seq=0 ttl=64 time=0.056 ms

--- second ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.056/0.056/0.056 ms
PING first (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.044 ms

--- first ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.044/0.044/0.044 ms
first
second

```

**Comment by tianon** [comment]
On `amd64`, `busybox:latest` _is literally_ `busybox:uclibc`: https://github.com/docker-library/official-images/blob/c85c21613ee36a8c7f80ea3a78cd373337709d02/library/busybox#L47

```console
$ docker images busybox:latest
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              f9b6f7f7b9d3        7 days ago          1.14MB
$ docker images busybox:uclibc
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             uclibc              f9b6f7f7b9d3        7 days ago          1.14MB
```

**Comment by arm64b** [comment]
Hmm, according to the CI test of moby and plug my local experiment(`uclibc` failed on both `amd64` and `arm64`), I guess the root cause is `busybox:latest` point to the `busybox:uclibc` on those 2 Arches, I don't know the reason why we use `uclibc` instead of `glibc` on the 2 arches only, but `ulibc` is targeted to the embedded and mobile system...

**Comment by arm64b** [comment]
Hello @tianon , do you have some plan to address this or what I can do sth here to close it ❓

**Comment by tianon** [comment]
Perhaps Docker's CI should simply use the glibc variant explicitly instead
of latest?  I'm fairly sure it's available on all the necessary
architectures.

Barring some way for the maintainers to reliably reproduce the problem,
it's very challenging to guess at what the problem might be and how to
debug/fix it.

**Comment by arm64b** [comment]
Fair enough, although we can reproduce this issue but indeed we can't figure out which exactly pkg result in this problem, maybe it will be helpful to check the pkg difference between uclibc and glibc, as imaged this is a time-consuming task. Currently I will explicitly point the busybox used in the Moby to the `busybox:glibc` instead of `busybox:latest`. So as last, my curiosity is the reason we assign the `busybox:latest` to `busybox:uclibc` on amd64 and arm64, while it's `busybox:glibc` on other Arches 😵

**Comment by tianon** [comment]
Since the only way to reliably reproduce this issue appears to be running Docker's own test suite (which is a very heavy reproducer), I'm going to close.

It'd be great to come up with a very simple reproducer, but even then we'll need to do more digging to figure out whether the issue is in BusyBox, uClibc, or in how we're building/configuring the two.
