### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by J-Ibarra** [docker-library/busybox#47]
How I cant add the curl to busybox?

**Comment by yosifkit** [comment]
You'd need a statically compiled `curl` and then `COPY` it into the image. You could just use wget:
```console
$ docker run -it --rm busybox
/ # curl
sh: curl: not found
/ # wget
BusyBox v1.28.4 (2018-05-22 17:00:17 UTC) multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
	[--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
	[-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	--spider	Only check URL existence: $? is 0 if exists
	-c		Continue retrieval of aborted transfer
	-q		Quiet
	-P DIR		Save to DIR (default .)
	-S    		Show server response
	-T SEC		Network read timeout is SEC seconds
	-O FILE		Save to FILE ('-' for stdout)
	-U STR		Use STR for User-Agent header
	-Y on/off	Use proxy
/ # 
```

**Comment by adamkdean** [comment]
This doesn't help when you need to use more functionality than wget has available, sadly.

**Comment by tianon** [comment]
If you need more functionality than BusyBox alone, then I'd recommend checking out Alpine, which is basically BusyBox plus their `apk` package manager (which allows you to easily install `curl` if you so need, for example).

**Comment by adamkdean** [comment]
Aye, I usually use alpine, but in this case I'm extending a busybox based image and need to copy in curl, meaning I need a statically compiled version of curl. I was just commenting on the suggestion of wget as an alternative. Thanks though!

**Comment by qdm12** [comment]
Why do we have wget but not curl in busybox by the way? If anyone knows 🤔 Why not curl instead of wget?

**Comment by yosifkit** [comment]
>Why do we have wget but not curl in busybox by the way? If anyone knows 🤔 Why not curl instead of wget?

Because `busybox` implements `wget` and not `curl`. https://git.busybox.net/busybox/tree/networking/wget.c?h=1_32_stable

**Comment by qdm12** [comment]
Thanks for the answer... although I believe it is the reason of my question 😉 Why isn't busybox supporting curl instead of wget? Is this a size problem? Especially since curl is under an MIT license AFAIK 🤔

**Comment by tianon** [comment]
BusyBox does not include `wget` -- BusyBox _reimplements_ a subset of `wget` (as they do with all the coreutils they include, etc).  That's the whole point of BusyBox.  The usage patterns of `curl` are significantly more complex, so implementing a subset of those would be a lot more complicated.

To illustrate:

```console
$ wget --help | wc -l
207

$ docker run --rm busybox wget --help 2>&1 | wc -l
20

$ docker run --rm busybox wget --help
BusyBox v1.32.1 (2021-04-07 19:47:14 UTC) multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
	[-o|--output-file FILE] [--header 'header: value'] [-Y|--proxy on/off]
	[--no-check-certificate]
	[-P DIR] [-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	--spider	Only check URL existence: $? is 0 if exists
	--no-check-certificate	Don't validate the server's certificate
	-c		Continue retrieval of aborted transfer
	-q		Quiet
	-P DIR		Save to DIR (default .)
	-S    		Show server response
	-T SEC		Network read timeout is SEC seconds
	-O FILE		Save to FILE ('-' for stdout)
	-o FILE		Log messages to FILE
	-U STR		Use STR for User-Agent header
	-Y on/off	Use proxy
```

If `curl` is something required for your use case, I would reiterate the advice from above: Alpine is `busybox` + a minimal package manager and `libc` implementation such that you can trivially do `apk add --no-cache curl` and get real `curl` (or even `apk add --no-cache wget` to get the "real" `wget` instead of BusyBox `wget`).

**Comment by qdm12** [comment]
Nice thanks so much for the explanations 👍. I would, from my semi ignorant point of view, that it helps to reduce the attack surface since busybox's wget is even simpler than the actual wget.

**Comment by tianon** [comment]
I mean, yes, but also very much no: https://github.com/docker-library/busybox/issues/80 (TLS validation is Broken-By-Design)

**Comment by qdm12** [comment]
Oh well, you just blew my mind 😄

So... I guess we should either have openssl somewhere or install e. g. Alpine's wget if we want proper TLS validation for the time being and foreseeable future right? Anyway sorry for the off-topic comment but this is definitely interesting knowledge 😉
