### ISSUE TITLE
Add support of Windows

### ISSUE THREAD

**Issue by feiskyer** [docker-library/busybox#50]
busybox image doesn't run on Windows, we should add windows support for it.

Refer https://github.com/kubernetes/kubernetes/pull/61097.
Refer https://github.com/e2e-win/k8s_images/blob/master/busybox/Dockerfile.

**Comment by tianon** [comment]
As I noted in https://github.com/kubernetes/kubernetes/pull/61097, this requires _upstream_ support for Windows which does not currently exist.  There are a couple discussions on their mailing list (I found a few interesting ones by searching for `site:busybox.net` combined with "Windows", "win32", and "mingw"), and I also went as far as trying to compile against MinGW without much success.

Barring actual upstream support for this, I'm sorry but there's not much we can do.  From what I can see, upstream needs some patching and also a champion to maintain support going forward.

If someone can demonstrate building unpatched sources from busybox.net for Windows, I would be thrilled to revisit this.

**Comment by dims** [comment]
@tianon when you say `upstream` which repository do you mean? is there a issue tracker there?

**Comment by feiskyer** [comment]
> this requires upstream support for Windows which does not currently exist

@tianon  I thought upstream means `docker-library/busybox`. Do you mean the code base of busybox itself?

**Comment by tianon** [comment]
I mean busybox.net -- they do have an issue tracker, but I believe they
prefer to see issues discussed on the mailing list first (they've got a
contributing doc somewhere on the site).
