### ISSUE TITLE
Missing arm32v6/busybox:glibc

### ISSUE THREAD

**Issue by anzevalher** [docker-library/busybox#58]
Would it be possible to create that image and release it even tho it's not officially supported, but would be nice to be able to generate all archs in one go(all others have it)?

**Comment by tianon** [comment]
The way we build our `glibc` variant is by using Debian as a base, and Debian does not support `arm32v6`, so by extension, we do not.  If you'd like to use `arm32v6`, unfortunately the `musl` variant is your only option.

**Comment by anzevalher** [comment]
ok, thank you for this information, didn't realize Debian doesn't support v6
