### ISSUE TITLE
Nslookup does not work in Kubernetes if omitting .svc.cluster.local suffix

### ISSUE THREAD

**Issue by Simon3** [docker-library/busybox#61]
Hi, after months of using busybox in Kubernetes with no problem and without changing anything to my busybox init-containers, yesterday I encountered a strange bug: if I omit to add the `.svc.cluster.local` suffix to nslookup, e.g. if I try to resolve `kubernetes.default`or `cassandra.cassandra`, it will end up with a NXDOMAIN answer and an exit status of 1. Note that from any other container than busybox, it works fine. 

```
/ # nslookup kubernetes.default
Server:		10.0.0.10
Address:	10.0.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer

/ # echo $?
1
```

But this works: 

```
/ # nslookup kubernetes.default.svc.cluster.local
Server:		10.0.0.10
Address:	10.0.0.10:53

Non-authoritative answer:
Name:	kubernetes.default.svc.cluster.local
Address: 10.0.0.1

*** Can't find kubernetes.default.svc.cluster.local: No answer

/ # echo $?
0
```

```
/ # cat /etc/resolv.conf 
nameserver 10.0.0.10
search flowr-besix-stay.svc.cluster.local svc.cluster.local cluster.local c.taktik-dev.internal google.internal
options ndots:5
```

In my chart I have always simply been using 'busybox', I'm not sure on which tag I am currently, all I could find is the hash of the image: 

```
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:bf510723d2cd2d4e3f5ce7e93bf1e52c8fd76831995ac3bd3f90ecc866643aff
```

Meanwhile, the workaround is just to use `nslookup cassandra.cassandra.svc.cluster.local` instead of `nslookup cassandra.cassandra`. 

Note that it doesn't seem to be the same bug as #48: 

```
/ # nslookup -type=a kubernetes.default
Server:		10.0.0.10
Address:	10.0.0.10:53

** server can't find kubernetes.default: NXDOMAIN

/ # echo $?
1
/ # nslookup -type=aaaa kubernetes.default
Server:		10.0.0.10
Address:	10.0.0.10:53

** server can't find kubernetes.default: NXDOMAIN

/ # echo $?
1
```

**Comment by wglambert** [comment]
This seems like an upstream issue and not something we can alleviate in the Dockerfile, currently there's no issue on Busybox's [bug tracker](https://bugs.busybox.net/buglist.cgi?quicksearch=nslookup) about this specific nslookup/networking problem.

The Dockerfile is just adding in the tarball https://github.com/docker-library/busybox/blob/1554579b4eb9ff41a5718b43824cf27e6f4893ca/glibc/Dockerfile#L1-L3


Using debian it works as expected
```console
$ kubectl run -it --rm --image=tianon/network-toolbox debian
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
root@bash-7f44b7546b-2zwjn:/# nslookup registry
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   registry.default.svc.cluster.local
Address: 10.43.162.109

root@bash-7f44b7546b-2zwjn:/# nslookup registry.default
Server:         10.43.0.10
Address:        10.43.0.10#53

Non-authoritative answer:
Name:   registry.default.svc.cluster.local
Address: 10.43.162.109
```

```console
$ kubectl run -it --rm --image=busybox:glibc busybox
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
/ # nslookup registry
Server:         10.43.0.10
Address:        10.43.0.10:53

Name:   registry.default.svc.cluster.local
Address: 10.43.162.109

** server can't find registry.svc.cluster.local: NXDOMAIN

** server can't find registry.cluster.local: NXDOMAIN


** server can't find registry.svc.cluster.local: NXDOMAIN

** server can't find registry.cluster.local: NXDOMAIN

/ # nslookup registry.default
Server:         10.43.0.10
Address:        10.43.0.10:53

** server can't find registry.default: NXDOMAIN

** server can't find registry.default: NXDOMAIN
```

**Comment by wglambert** [comment]
And this is probably the same root issue of https://github.com/docker-library/busybox/issues/48

https://github.com/docker-library/busybox/issues/48#issuecomment-411807171
>See this issue:
>https://github.com/kubernetes/kubernetes/issues/66924

https://github.com/kubernetes/kubernetes/issues/66924#issuecomment-411804435
>It looks like DNS inside busybox does not work properly.
>At least it works for me with busybox images <= 1.28.4

**Comment by 1player** [comment]
Doesn't seem to work for me, even when appending `.svc.cluster.local` at the end of the name. Other network tools like telnet work perfectly, so it's just nslookup being broken.

In fact, I was testing something unrelated, and nslookup managed to resolve _some_ addresses but not all, after a while, on another instance of busybox, it couldn't resolve anything at all.

**Comment by neriksso** [comment]
Also came across this and our workaround is using `busybox:1.28`.

**Comment by tianon** [comment]
Again, as in #48, this is an upstream BusyBox issue more appropriately discussed on their bugtracker (https://bugs.busybox.net) -- we're simply building their upstream sources verbatim against three libc variants.

For what it's worth, the sentiment I get from https://bugs.busybox.net/show_bug.cgi?id=11161#c3 is that BusyBox's `nslookup` command should be considered deprecated entirely, but also using `busybox:1.28` appears to work for most users.  That being said, please take further discussion of this issue to the upstream bug tracker.
