### ISSUE TITLE
After upgrade to Alpine 3.10 timeout syntax is different

### ISSUE THREAD

**Issue by wolkym** [docker-library/busybox#63]
It looks like `timeout` syntax has changed in Busybox 1.30.1. `-t` parameter is not available anymore. This affects update from 18.09.5 to 18.09.6

# WAS
https://git.busybox.net/busybox/tree/coreutils/timeout.c?h=1_29_stable#n66
```
//usage:#define timeout_trivial_usage
//usage:       "[-t SECS] [-s SIG] PROG ARGS"
```

# NOW
https://git.busybox.net/busybox/tree/coreutils/timeout.c?h=1_30_stable#n66
```
//usage:#define timeout_trivial_usage
//usage:       "[-s SIG] SECS PROG ARGS"
//usage:#define timeout_full_usage "\n\n"
//usage:       "Runs PROG. Sends SIG to it if it is not gone in SECS seconds.\n"
//usage:       "Default SIG: TERM."
```

It was discussed already [here](https://github.com/vishnubob/wait-for-it/issues/5#issuecomment-490076788)

**Comment by yosifkit** [comment]
First, the busybox in Alpine based images has nothing to do with this image. This image is a build of busybox upstream busybox releases.

This is a duplicate https://github.com/docker-library/docker/issues/162.
