### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by frafra** [docker-library/busybox#64]
`wget` cannot fetch data from HTTPS websites.

```
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer
```

**Comment by wglambert** [comment]
The notice `note: TLS certificate validation not implemented` isn't an error in itself, so the `. . . handshake failure` is the actual error.
Perhaps you're getting redirected to a non https server?


```console
$ docker run -it --rm busybox sh

# wget https://github.com/docker-library/busybox/archive/master
.zip
Connecting to github.com (192.30.253.112:443)
wget: note: TLS certificate validation not implemented
Connecting to codeload.github.com (192.30.253.121:443)
saving to 'master.zip'
master.zip           100% |*****************| 12795  0:00:00 ETA
'master.zip' saved

# unzip master.zip 
Archive:  master.zip
   creating: busybox-master/
  inflating: busybox-master/.travis.yml
  inflating: busybox-master/README.md

# wget https://www.google.com
Connecting to www.google.com (172.217.11.68:443)
wget: note: TLS certificate validation not implemented
saving to 'index.html'
index.html           100% |*****************| 12225  0:00:00 ETA
'index.html' saved

# cat index.html | head -c 100
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content
```

**Comment by ThisGuyCodes** [comment]
How can we get certificate validation here? Or is there simply no way to safely connect from a busybox image.

**Comment by tianon** [comment]
My understanding is that it would require embedding a "full" SSL implementation such as OpenSSL in addition to somehow getting `ca-certificates`.  I think users who need that are better off using a minimal distro like Alpine Linux which includes BusyBox with working SSL that has certificate verification out of the box (and is still ~4MB, so a very moderate increase over the size of this image, but also includes a full package manager).

**Comment by wglambert** [comment]
Assuming this is resolved, and since I can't reproduce an error with wget and https I'm going to close.
