### ISSUE TITLE
wget doesn't support --no-directories option

### ISSUE THREAD

**Issue by tumluliu** [docker-library/busybox#78]
Is the wget bundled in busybox a full-functional version? It doesn't support `--no-directories` option, also `--version` option returns `unrecognized option`

**Comment by wglambert** [comment]
Busybox utils are not full-featured versions https://busybox.net/about.html
>BusyBox combines tiny versions of many common UNIX utilities into a single small executable. It provides replacements for most of the utilities you usually find in GNU fileutils, shellutils, etc. The utilities in BusyBox generally have fewer options than their full-featured GNU cousins; however, the options that are included provide the expected functionality and behave very much like their GNU counterparts. BusyBox provides a fairly complete environment for any small or embedded system.

```console
$ docker run -it --rm busybox sh

/ # wget --help
BusyBox v1.31.1 (2019-12-23 19:20:27 UTC) multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
        [-o|--output-file FILE] [--header 'header: value'] [-Y|--proxy on/off]
        [-P DIR] [-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

        --spider        Only check URL existence: $? is 0 if exists
        -c              Continue retrieval of aborted transfer
        -q              Quiet
        -P DIR          Save to DIR (default .)
        -S              Show server response
        -T SEC          Network read timeout is SEC seconds
        -O FILE         Save to FILE ('-' for stdout)
        -o FILE         Log messages to FILE
        -U STR          Use STR for User-Agent header
        -Y on/off       Use proxy
```

**Comment by tumluliu** [comment]
Understood. Many thanks! @wglambert 
Can be closed
