### ISSUE TITLE
Unable to find group dbus

### ISSUE THREAD

**Issue by ozlerhakan** [docker-library/busybox#8]
Hi,

I am not sure whether is the right place for this issue or not but, here it is,

Just testing this command mentioned in [the Additional groups](https://github.com/docker/docker/blob/ab8da94531ba77feee1931923be812354fbd2b2c/docs/reference/run.md#additional-groups) section ,I get the following error:

```
$ docker run -it --rm --group-add audio  --group-add dbus --group-add 777 busybox id
Unable to find group dbus
Error response from daemon: Cannot start container 53b17f2f45878e0a6f40e43d7f993e384e29e89d34b86b3af7f0b9ea9557866f: [8] System error: Unable to find group dbus
```

Simply taking  `dbus` out, (also `-it` is redundant), I see the result with no error:

```
$ docker run --rm --group-add audio  --group-add 777 busybox id
uid=0(root) gid=0(root) groups=10(wheel),29(audio),777
```
Seems like `dbus` does not exist on the current user list of busybox:latest.

**Comment by tianon** [comment]
Why do you need a group named "dbus" inside the container? Is one of the
core applets not working without it?

If you're wanting to have your host's dbus group you will want/have to
specify it directly by ID.

**Comment by ozlerhakan** [comment]
I actually don't want this group. I just tested this command mentioned on the doc, and got an error.

**Comment by tianon** [comment]
Which doc is it that mentions it?  One of Docker's docs, or the readme for
this image?

**Comment by ozlerhakan** [comment]
I mentioned in my first comment but here is the related doc: https://github.com/docker/docker/blob/master/docs/reference/run.md#additional-groups

**Comment by tianon** [comment]
Doh!  Indeed you did, my apologies.  I'll go see about making a PR to fix that doc, thanks! :+1:

**Comment by tianon** [comment]
https://github.com/docker/docker/pull/20233 :+1:

(Since this isn't exactly relevant to this repository anymore, I'm closing this issue, but feel free to comment further and thanks for reporting it and being patient with my inability to read! :innocent:)

**Comment by ozlerhakan** [comment]
np, you're welcome @tianon , the PR is OK, you may also consider to take `-it` out, since they actually are redundant :)

**Comment by tianon** [comment]
Excellent point!  Updated. :+1:
