### ISSUE TITLE
More general "swiss army knife" including more tools such as `curl`?

### ISSUE THREAD

**Issue by fzyzcjy** [docker-library/busybox#86]
Thanks for this powerful tool! However, we often need some more tools, such as `curl`. Is there a "fat busybox" that everyone uses? Thanks!

**Comment by tianon** [comment]
What you've described is essentially Alpine Linux 😄

It's `busybox` but with a very small package manager for adding more tools easily (like `curl`).

**Comment by fzyzcjy** [comment]
Thanks very much! I will try that :)
