### ISSUE TITLE
BusyBox 1.32.1 (stable)

### ISSUE THREAD

**Issue by ko1nksm** [docker-library/busybox#93]
The latest version is already 1.33.0 (unstable), but the stable version, 1.32.1, is currently not available.

https://www.busybox.net/

> 1 January 2021 -- BusyBox 1.32.1 (stable)
> 
> Bug fix release. 1.32.1 fixes a case where in ash, "wait" never finishes.
> 
> 29 December 2020 -- BusyBox 1.33.0 (unstable)

**Comment by tianon** [comment]
Good point, thanks for the push! (#94)
